name: Go

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      matrix:
        working-directory:
          - .
          - ./usegoalie
    defaults:
      run:
        working-directory: ${{ matrix.working-directory }}
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v6
        with:
          go-version-file: ${{ matrix.working-directory }}/go.mod
      - run: go vet ./...
      - run: go fmt ./...
      - run: go run golang.org/x/tools/cmd/goimports@latest -w ./...
      - uses: autofix-ci/action@v1
      - run: go build -v ./...
      - run: go test -v ./...
